// Code generated by mockery v1.0.0. DO NOT EDIT.

package pack

import (
	context "context"

	pack "github.com/buildpacks/pack"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Build provides a mock function with given fields: ctx, opts
func (_m *Client) Build(ctx context.Context, opts pack.BuildOptions) error {
	ret := _m.Called(ctx, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pack.BuildOptions) error); ok {
		r0 = rf(ctx, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
