= riff CLI tool

We provide a CLI tool written in Go that makes it easy to create and deploy functions.

The CLI is built with https://github.com/spf13/cobra[cobra]

* link:docs/riff.md[Documentation]

== [[CLI]]Install the current riff CLI release

Install the CLI by following the instructions on the https://github.com/projectriff/riff/releases[riff release page].


=== [[cli-config]]riff CLI configuration

The riff CLI can be configured either using environment variables or using a config file. 
The config file to be used can be set using `--config` option and it defaults to `$HOME/.riff.yaml`.

Environment variables are prefixed with `RIFF_` and the variables from the following example are supported:

```
RIFF_USERACCOUNT=myaccount
RIFF_NAMESPACE=test
```

For the config file, you can create a `~/.riff.yaml` file with something like the following content:

```
useraccount: myaccount
namespace: test
```

=== [[cli-completion]]riff CLI bash completion

The riff CLI command supports generating a bash completion file in the same way as the `kubectl` command does.

==== [[cli-completion-macos]]riff CLI bash completion on macOS

If you use https://brew.sh/[Homebrew] on a Mac you can install the completion file using:

```
brew install bash-completion
riff completion bash > $(brew --prefix)/etc/bash_completion.d/riff 
```

==== [[cli-completion-linux]]riff CLI bash completion on Linux

If you use Linux you can installl the completion file using:

```
. <(riff completion bash) 
```

TIP: You can edit your `.bashrc` file to have this automatically loaded on future shell runs.

== Building from source

```
go get -d github.com/projectriff/riff/...
cd $(go env GOPATH)/src/github.com/projectriff/riff
make -C riff-cli/ build
```

== Add riff binary to PATH
```
cd $(go env GOPATH)/src/github.com/projectriff/riff
make -C riff-cli/ install
```
NOTE: This installs the CLI in the `bin` subdirectory of the first directory listed in `$GOPATH`.

== Running tests
```
cd $(go env GOPATH)/src/github.com/projectriff/riff
make -C riff-cli/ test
```
