#!/bin/bash
set -e -v

./build-java-function-invoker ${1:-''} ${2:-''}
./build-node-function-invoker ${1:-''} ${2:-''}
./build-shell-function-invoker ${1:-''} ${2:-''}
./build-python2-function-invoker ${1:-''} ${2:-''}

