#!/bin/bash

# Helper script for building a project.
# Accepts the following arguments:
# $1 path (required)                             - the path to cd into for building
# $2 remote alias (optional)                     - if set together with $3, will fetch latest state from remote and checkout the given branch
# $3 branch name (optional)                      -   see above. The default is to build the directory in its current state
# $4 build command (optional, default = "make")  - the command to run to build the project

set -e 

BUILD_COMMAND=${4:-make}

pushd $1
    if [ -z $2 ]; then
        eval "$BUILD_COMMAND"
    else
        if [ -z $3 ]; then
            echo "Branch name (\$3) required when specifying a remote ($2)"; exit 1;
        fi
        git fetch $2 
        git checkout $2/$3 
        eval "$BUILD_COMMAND" 
        git checkout -
    fi
popd
