= Installing the riff development version using Helm

== [[pre-req]]Prerequisites

* A running 1.7+ Kubernetes cluster

* Kubernetes CLI `kubectl` installed and on the local system PATH.
We recommend using the same version or later as the Kubernetes cluster you are using.

* Helm, you need helm installed, see instructions link:https://github.com/kubernetes/helm/blob/master/README.md#install[here]. 

* Docker, you only need Docker when building custom versions of riff components or the samples.
We have used Docker version 17.x or later.

== Install Helm server component

You need to already have the Helm client installed, see link:#pre-req[Prerequisites].

For a cluster that does not have RBAC enabled use:

[source, bash]
----
helm init
----

It gets a bit more complicated if the cluster has RBAC enabled. The Helm project describes the https://docs.helm.sh/using_helm/#best-practices-for-securing-helm-and-tiller[Best Practices for Securing Helm and Tiller] in their documentation. This can be fairly involved and for less critical development clusters it is easier to configure the Helm tiller server to run with cluster-admin privileges using a service account in the `kube-system` namespace.

If you are using a GKE cluster and don't have cluster admin rights you can run the following to grant yourself the admin role, as long as you know the admin password. You can look up the password using the `Show credentials` link on the cluster details page.

```
export GKE_ADMIN_PASSWD=<the admin password>
export GKE_USER=$(gcloud config get-value core/account)
export GKE_PREFIX=$(echo $GKE_USER | awk -F'@' '{print $1}')
kubectl --username=admin --password=$GKE_ADMIN_PASSWD create clusterrolebinding ${GKE_PREFIX}-cluster-admin-binding --clusterrole=cluster-admin --user=${GKE_USER}
```

You should now have cluster admin rights and can run the following to install Helm's server component:

[source, bash]
----
kubectl -n kube-system create serviceaccount tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account=tiller
----

TIP: To verify that the tiller pod has started execute the following command: `kubectl get pod --namespace kube-system -l app=helm` and you should see the `tiller` pod running.

== Add the riff repository to your helm configuration

Riff offers helm charts for deploying the FaaS and its required services to a Kubernetes Cluster.
The following instructions cover how to configure helm to be able to install the riff charts.

Run the following commands to add the repository:

[source, bash]
----
helm repo add projectriff https://riff-charts.storage.googleapis.com
helm repo update
----

Run the following command to see that the `riff` chart is available and also what versions you can install:

[source, bash]
----
helm search riff -l
----

== [[devel]]Install a riff development version

All riff components will be deployed into a `riff-system` namespace. 
Any functions that are developed can be deployed into any other namespace including the `default` namespace.

We provide a lightweight single node Kafka installation with the `projectriff/kafka` chart. 
This works well for development purposes and it can be installed together with the riff chart by providing `--set kafka.create=true` when installing the riff chart.

[TIP]
====
If you want to install Kafka using the three-node kafka/zookeeper service provided by the Kubeapps `incubator/kafka` chart, then you should use:

[source, bash]
----
helm install --name transport --namespace riff-system incubator/kafka
----

Just be aware that this chart requires significantly more resources to run.

When you install the riff chart during the next step, you need to add some config settings so that the riff components can find the Kafka service.
Add the following config settings instead of `--set kafka.create=true` to the `helm install` command that you use:

[source, bash]
----
--set kafka.broker.nodes=transport-kafka.riff-system:9092 --set kafka.zookeeper.nodes=transport-zookeeper.riff-system:2181
----

====

WARNING: Beginning with Minikube v0.26.0 the default bootstrapper has changed to kubeadm which enables RBAC.
To create a Minikube cluster without RBAC enabled you should use the localkube bootstrapper. You can do that with the following command `minikube start --memory=4096 --bootstrapper=localkube`.

=== Install "devel" version of riff chart

Choose one of the following installations options:

- *Install "devel" version of riff chart with published snapshot builds of the components*
+
Install the development version of the riff chart in the `riff-system` namespace.
When using Minikube configure the httpGateway to use `NodePort` with:
+
[source, bash]
----
helm install --name projectriff --namespace riff-system projectriff/riff --devel --set kafka.create=true --set httpGateway.service.type=NodePort
----
+
[NOTE]
====
For a cluster that supports `LoadBalancer` leave out the `--set httpGateway.service.type=NodePort` option.
For a cluster that doesn't use RBAC add the `--set rbac.create=false` option.
====

- *Install "devel" version of riff chart with locally built snapshot components with Minikube*
+
Clone the https://github.com/projectriff/riff[riff] repository.
The `helm install` commands in this section assume you are in the root directory of that project.
+
[TIP]
====

Configure Docker to use the Docker environment running in minikube:

[source, bash]
----
eval $(minikube docker-env)
----
====
+
Build the riff components following the link:README.adoc#manual[manual build and deploy] instructions.
+
To install locally built Docker images with Helm on minikube, use the `--devel` option which uses the chart version that has snapshot versions:
+
[source, bash]
----
helm install projectriff/riff --name projectriff --namespace riff-system --devel --set kafka.create=true --set rbac.create=false --set httpGateway.service.type=NodePort
----

=== Customizing the Installation

The Helm chart contains a https://github.com/projectriff/riff/blob/master/helm-charts/riff/values.yaml[values.yaml]
file that specifies the default values used when installing the chart.
They can all be overridden by using the flag `--set` as described in the documentation
for https://docs.helm.sh/helm/#helm-install[Helm Install].

Some values that you might want to override are listed in the
https://github.com/projectriff/riff/blob/master/helm-charts/riff/README.md#configuration[Configuration section of the README].

The following are some scenarios for customizing your installation:

NOTE: The same customizations work for all of the riff components: `functionController`, `topicController`, and `httpGateway`

- *Overriding the version of a riff component:*
+
To set the version tag for the `functionController` to `0.0.5-build.1` use something like the following:
+
[source, bash]
----
helm install projectriff/riff --name projectriff --namespace riff-system --set functionController.image.tag=0.0.5-build.1 --devel --set kafka.create=true --set rbac.create=false --set httpGateway.service.type=NodePort
----

- *Overriding the image repository and version tag of a riff component with a custom built component image:*
+
To set the image repository to `mycustom/function-controller` and the version tag to `0.0.5-test.1` for
the `functionController`, use something like the following:
+
[source, bash]
----
helm install projectriff/riff --name projectriff --namespace riff-system --set functionController.image.repository=mycustom/function-controller --set functionController.image.tag=0.0.5-test.1 --devel --set kafka.create=true --set rbac.create=false --set httpGateway.service.type=NodePort
----

- *Overriding the version of the `sidecar` component:*
+
The `sidecar` component is only used by the `functionController`, so to set the version for
the `sidecar` to `0.0.5-build.1` use something like the following:
+
[source, bash]
----
helm install projectriff/riff --name projectriff --namespace riff-system --set functionController.sidecar.image.tag=0.0.5-build.1 --devel --set kafka.create=true --set rbac.create=false --set httpGateway.service.type=NodePort
----

=== To tear it all down

[source, bash]
----
helm delete --purge projectriff
----
