#!/bin/bash

./mvnw dockerfile:build -pl \
topic-controller,\
topic-gateway,\
event-dispatcher,\
zipkin-server,\
function-invokers/java-function-invoker,\
function-invokers/node-function-invoker,\
function-invokers/python2-function-invoker,\
function-invokers/shell-function-invoker
