#!/bin/bash

./mvnw docker:build -pl \
topic-controller,\
topic-gateway,\
event-dispatcher,\
function-sidecar,\
zipkin-server,\
function-invokers/java-function-invoker,\
function-invokers/node-function-invoker,\
function-invokers/shell-function-invoker
