= Riff: a FaaS for Kubernetes - Getting Started

== Installation

=== [[helm]]Helm install of Riff FaaS

Riff offers a Helm Chart for deploying the FaaS and its required services to a Kubernetes Cluster.
The following instructions cover how to initialize Helm and install Riff FaaS on the Minikube cluster.

==== Prerequisites

* A running 1.7 Kubernetes cluster with at least 4GB of memory. These instructions assume minikube for now.

----
minikube start --cpus=4 --memory=4096 --disk-size=64g
----

==== Install Helm

Helm is comprised of 2 components: one is the client (Helm) the other is the server component (Tiller). The Helm client is run on your local machine and can be installed using the instructions found here: https://github.com/kubernetes/helm/blob/master/README.md#install

Once you have Helm client installed you can install the server component.

For a cluster that does not have RBAC enabled use:

----
helm init
----

For a cluster that has RBAC enabled use:

----
kubectl -n kube-system create serviceaccount tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account=tiller
----

NOTE: To verify that the Tiller pod has started execute the following command: `kubectl get pod --namespace kube-system` and you should see the `tiller` pod running.

==== Add the Riff repository to your Helm environment

Run the following commands to add the repository:

----
helm repo add riffrepo https://riff_charts.storage.googleapis.com
helm repo update riffrepo
----

==== Install Riff FaaS helm chart

Install the Riff Helm chart as follows:

- `helm search riffrepo/riff` and identify the version you're looking to install (use the latest one if unsure)

For a cluster that does not have RBAC enabled use:

----
- `helm install riffrepo/riff --name=faas --version=<version>`
----

For a cluster that does have RBAC enabled use:

----
- `helm install riffrepo/riff --name=faas --version=<version> --set create.rbac=true`
----

You should see a number of resources get created in your Minikube. You can see them all using:

----
kubectl get svc,deployments,pods,jobs,functions,topics
----

==== Clone the repo

To work with the demos and Metrics Dashboard you need a clone of the Riff repo:

----
git clone https://github.com/projectriff/riff.git
----

==== Enable Metrics and Tracing Dashboards

You can enable each dashboard by setting flags for the Helm release. For the Metrics Dashboard use
`--set enable.metricsDashboard=true` and for the Tracing Dashboard use `--set enable.tracingDashboard=true`.

These flags can be set when installing the chart or you can apply them during an upgrade operation.
Here is an example of upgrading the release and enabling the Metrics Dashboard:

----
helm upgrade riff riffrepo/riff --set enable.metricsDashboard=true
----

See how to use the link:Monitoring.adoc#dashboards[dashboards] and run some link:samples/README.adoc[samples].

==== To tear it all down

----
helm delete riff --purge
----

==== Installing Local Builds

When building snapshot images locally, pass in a reference to the `values-snapshot.yaml` file, which contains snapshot tags:

- `helm install riffrepo/riff --name=faas --values=config/values-snapshot.yaml`
