= Getting Started with riff

Riff is designed to use https://kubernetes.io/[Kubernetes] features for running Functions in response to Events.
This guide covers installing riff using https://helm.sh/[Helm], which is a commonly used package manager for Kubernetes. 

== Prerequisites

* A running 1.7+ Kubernetes cluster

* Kubernetes CLI `kubectl` installed and on the local system PATH. We recommend using the same version or later as the Kubernetes cluster you are using.

* Docker, if you plan on building samples or your own functions then you will need Docker installed. We have used Docker version 17.x or later.

== [[helm]]Install Helm

Helm is comprised of two components: one is the client (helm) the other is the server component (tiller). The helm client runs on your local machine and can be installed using the instructions found https://github.com/kubernetes/helm/blob/master/README.md#install[here]

Once you have the helm client installed you can install the server component.

For a cluster that does not have RBAC enabled use:

[source, bash]
----
helm init
----

[NOTE]
====
It gets a bit more complicated if the cluster has RBAC enabled. The Helm project describes the https://docs.helm.sh/using_helm/#best-practices-for-securing-helm-and-tiller[Best Practices for Securing Helm and Tiller] in their documentation. This can be fairly involved and for less critical development clusters it is easier to configure the Helm tiller server to run with cluster-admin privileges using a service account in the `kube-system` namespace. You should have cluster admin rights and run the following:

[source, bash]
----
kubectl -n kube-system create serviceaccount tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account=tiller
----

====

TIP: To verify that the tiller pod has started execute the following command: `kubectl get pod --namespace kube-system -l app=helm` and you should see the `tiller` pod running.

== Add the riff repository to your helm configuration

Riff offers helm charts for deploying the FaaS and its required services to a Kubernetes Cluster.
The following instructions cover how to configure helm to be able to install the riff charts.

Run the following commands to add the repository:

[source, bash]
----
helm repo add projectriff https://riff-charts.storage.googleapis.com
helm repo update
----

Run the following command to see that the `riff` chart is available and also what versions you can install:

[source, bash]
----
helm search riff -l
----

== [[current]]Install the current riff release

Starting with the 0.0.4 version we have separated the Kafka installation from the riff chart. This requires an extra step of installing Kafka in order to use riff. You can use the single-node Kafka chart provided by riff or the three-node kafka/zookeeper service provided by Kubeapps.

=== Install Kafka chart

We provide a lightweight single node Kafka installation in the `projectriff/kafka` chart. This works well for development purposes.

Create the `riff-system` namespace:

[source, bash]
----
kubectl create namespace riff-system
----

Install the kafka/zookeeper service provided by riff using:

[source, bash]
----
helm install --name transport --namespace riff-system projectriff/kafka
----

[TIP]
====
Alternatively, install the three-node kafka/zookeeper service provided by the Kubeapps `incubator/kafka` chart using:

[source, bash]
----
helm install --name transport --namespace riff-system incubator/kafka
----

Just be aware that this chart requires significantly more resources to run.
====

=== Install riff using a Kubernetes cluster supporting LoadBalancer

Install the riff helm chart as follows:

For an install with default configuration and no RBAC enabled use:

[source, bash]
----
helm install projectriff/riff --version 0.0.4 --name demo --namespace riff-system --set rbac.create=false
----

[NOTE]
====
For a cluster that has RBAC enabled, use the following (since `rbac.create` is `true` by default):

[source, bash]
----
helm install projectriff/riff --version 0.0.4 --name demo --namespace riff-system
----
====

=== Install riff using a Kubernetes cluster not supporting LoadBalancer (e.g. minikube)

For `NodePort` service types (e.g. running on Minikube) configure the httpGateway to use `NodePort`:

[source, bash]
----
helm install projectriff/riff --version 0.0.4 --name demo --namespace riff-system --set rbac.create=false --set httpGateway.service.type=NodePort
----

[NOTE]
====
For a cluster that has RBAC enabled, use the following (since `rbac.create` is `true` by default):

[source, bash]
----
helm install projectriff/riff --version 0.0.4 --name demo --namespace riff-system --set httpGateway.service.type=NodePort
----
====

=== Verify the installation

You should see a number of resources get created in your cluster. You can see them all using:

[source, bash]
----
kubectl get svc,deployments,pods,functions,topics
----

=== Components installed by the chart

The provided Helm chart installs the following components:

* Topic Controller - the controller that watches the Topic resources and creates new topics in Kafka

* Function Controller - the controller that watches the Function resources and deploys function images together with the sidecar image

* HTTP Gateway - the external facing gateway that listens for data posted to the various topics and forwards the data as a message for the corresponding Kafka topic

=== To tear it all down

[source, bash]
----
helm delete --purge demo
----

== [[CLI]]Install the current riff CLI tool

Starting with the 0.0.4 version we provide a CLI tool written in Go that makes it easy to create and deploy functions.
Install the CLI by following the instructions on the https://github.com/projectriff/riff/releases[riff release page].

=== [[cli-config]]riff CLI configuration

The riff CLI can be configured either using environment variables or using a config file. 
The config file to be used can be set using `--config` option and it defaults to `$HOME/.riff.yaml`.

Environment variables are prefixed with `RIFF_` and the variables from the following example are supported:

```
RIFF_VERSION=0.0.5
RIFF_USERACCOUNT=myaccount
RIFF_NAMESPACE=test
```

For the config file, you can create a `~/.riff.yaml` file with something like the following content:

```
riffVersion: 0.0.5
useraccount: myaccount
namespace: test
publishNamespace: riff-system
```

=== [[cli-completion]]riff CLI bash completion

The riff CLI command supports generating a bash completion file in the same way as the `kubectl` command does.

==== [[cli-completion-macos]]riff CLI bash completion on macOS

If you use https://brew.sh/[Homebrew] on a Mac you can install the completion file using:

```
brew install bash-completion
riff completion bash > $(brew --prefix)/etc/bash_completion.d/riff 
```

==== [[cli-completion-linux]]riff CLI bash completion on Linux

If you use Linux you can installl the completion file using:

```
. <(riff completion bash) 
```

TIP: You can edit your `.bashrc` file to have this automatically loaded on future shell runs.
