= Getting Started with riff

== Installation

=== [[helm]]Helm install of riff

Riff offers a helm chart for deploying the FaaS and its required services to a Kubernetes Cluster.
The following instructions cover how to initialize helm and install riff.

==== Prerequisites

* A running 1.7+ Kubernetes cluster

If using Minikube, we recommend at least 4GB of memory:

----
minikube start --memory=4096
----

==== Install Helm

Helm is comprised of 2 components: one is the client (helm) the other is the server component (tiller). The helm client runs on your local machine and can be installed using the instructions found here: https://github.com/kubernetes/helm/blob/master/README.md#install

Once you have the helm client installed you can install the server component.

For a cluster that does not have RBAC enabled use:

----
helm init
----

For a cluster that has RBAC enabled use:

----
kubectl -n kube-system create serviceaccount tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account=tiller
----

NOTE: To verify that the tiller pod has started execute the following command: `kubectl get pod --namespace kube-system` and you should see the `tiller` pod running.

==== Add the riff repository to your helm environment

Run the following commands to add the repository:

----
helm repo add riffrepo https://riff-charts.storage.googleapis.com
helm repo update riffrepo
----

==== Install the riff helm chart

Install the riff helm chart as follows:

For an install with default configuration and no RBAC enabled use:

----
helm install riffrepo/riff --name demo
----

For a cluster that has RBAC enabled add `--set create.rbac=true`:

----
helm install riffrepo/riff --name demo --set create.rbac=true
----

You should see a number of resources get created in your cluster. You can see them all using:

----
kubectl get svc,deployments,pods,functions,topics
----

==== Customizing the Configuration

Clone the https://github.com/projectriff/riff[riff] repository.
The `helm install` commands in this section assume you are in the root directory of that project.

For `NodePort` service types (e.g. running on Minikube) add `--values helm/values-nodeport.yaml`:

----
helm install riffrepo/riff --name demo --values helm/values-nodeport.yaml
----

To install locally built Docker images, use the `values-snapshot.yaml` file, which overrides image tags with snapshot versions:

----
helm install riffrepo/riff --name demo --values helm/values-snapshot.yaml
----

==== Enable Metrics and Tracing Dashboards

You can enable each dashboard by setting flags for the helm release.
For the Metrics Dashboard use `--set enable.metricsDashboard=true` and for the Tracing Dashboard use `--set enable.tracingDashboard=true`.

These flags can be set when installing the chart or you can apply them during an upgrade operation.
Here is an example of upgrading the release and enabling the Metrics Dashboard:

----
helm upgrade demo riffrepo/riff --set enable.metricsDashboard=true
----

See how to use the link:Monitoring.adoc#dashboards[dashboards] and run some link:samples/README.adoc[samples].

==== To tear it all down

----
helm delete demo --purge
----
