= Getting Started with riff

Riff is designed to use https://kubernetes.io/[Kubernetes] features for running Functions in response to Events.
This guide covers installing riff using https://helm.sh/[Helm], which is a commonly used package manager for Kubernetes. 

== Prerequisites

* A running 1.7+ Kubernetes cluster

* Kubernetes CLI `kubectl` installed and on the local system PATH. We recommend using the same version or later as the Kubernetes cluster you are using.

* Docker, if you plan on building samples or your own functions then you will need Docker installed. We have used Docker version 17.x or later.

== [[helm]]Install Helm

Helm is comprised of 2 components: one is the client (helm) the other is the server component (tiller). The helm client runs on your local machine and can be installed using the instructions found https://github.com/kubernetes/helm/blob/master/README.md#install[here]

Once you have the helm client installed you can install the server component.

For a cluster that does not have RBAC enabled use:

[source, bash]
----
helm init
----

For a cluster that has RBAC enabled use:

[source, bash]
----
kubectl -n kube-system create serviceaccount tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account=tiller
----

NOTE: To verify that the tiller pod has started execute the following command: `kubectl get pod --namespace kube-system -l app=helm` and you should see the `tiller` pod running.

== Add the riff repository to your helm configuration

Riff offers helm charts for deploying the FaaS and its required services to a Kubernetes Cluster.
The following instructions cover how to configure helm to be able to install the riff charts.

Run the following commands to add the repository:

[source, bash]
----
helm repo add riffrepo https://riff-charts.storage.googleapis.com
helm repo update
----

Run the following command to see that the `riff` chart is available and also what versions you can install:

[source, bash]
----
helm search riff -l
----

== [[current]]Install the current riff release

=== Install riff using a Kubernetes cluster supporting LoadBalancer

Install the riff helm chart as follows:

For an install with default configuration and no RBAC enabled use:

[source, bash]
----
helm install riffrepo/riff --version 0.0.3 --name demo
----

[NOTE]
====
For a cluster that has RBAC enabled add `--set create.rbac=true`:

[source, bash]
----
helm install riffrepo/riff --name demo --set create.rbac=true
----
====

[WARNING]
====
The 0.0.3 version of riff needs a fix to the RBAC configuration that is provided in version `0.0.3-rbac` of the chart. Use the following command to install riff `0.0.3` with RBAC enabled:

----
helm install riffrepo/riff --version 0.0.3-rbac --name demo
----
====

=== Install riff using a Kubernetes cluster not supporting LoadBalancer (e.g. minikube)

For `NodePort` service types (e.g. running on Minikube) configure the httpGateway to use `NodePort`:

[source, bash]
----
helm install riffrepo/riff --version 0.0.3 --name demo --set httpGateway.service.type=NodePort
----

[NOTE]
====
For a cluster that has RBAC enabled add `--set create.rbac=true`:

[source, bash]
----
helm install riffrepo/riff --name demo --set create.rbac=true --set httpGateway.service.type=NodePort
----
====

[WARNING]
====
The 0.0.3 version of riff needs a fix to the RBAC configuration that is provided in version `0.0.3-rbac` of the chart. Use the following command to install riff `0.0.3` with RBAC enabled:

----
helm install riffrepo/riff --version 0.0.3-rbac --name demo --set httpGateway.service.type=NodePort
----
====

=== Verify the installation

You should see a number of resources get created in your cluster. You can see them all using:

[source, bash]
----
kubectl get svc,deployments,pods,functions,topics
----

=== Components installed by the chart

The provided Helm chart installs the following components:

* Kafka and Zookeeper - the message broker used by the riff components

* Topic Controller - the controller that watches the Topic resources and creates new topics in Kafka

* Function Controller - the controller that watches the Function resources and deploys function images together with the sidecar image

* HTTP Gateway - the external facing gateway that listens for data posted to the various topics and forwards the data as a message for the corresponding Kafka topic

=== To tear it all down

[source, bash]
----
helm delete --purge demo
----
