#!/bin/bash

svc=$(kubectl get svc -l component=topic-gateway -o jsonpath='{.items}')
if [[ $svc == "[]" ]] ; then
  echo "Unable to locate the topic-gateway"
  exit 1
else
  port=$(kubectl get svc -l component=topic-gateway -o jsonpath='{.items[0].spec.ports[?(@.name == "http")].nodePort}')
fi

count=${3:-1}
pause=${4:-0}
address=$(minikube ip)

for ((i=1; i<=$count; i++)); do
	curl -H "Content-Type: text/plain" http://$address:$port/messages/$1 -d "$2"
	sleep $pause
done

