#!/bin/bash

# look for a local deploy
svc=$(kubectl get svc -l app=topic-gateway -o jsonpath='{.items}')
if [[ $svc == "[]" ]] ; then
  # look for a helm deploy
  svc=$(kubectl get svc -l component=topic-gateway -o jsonpath='{.items}')
  if [[ $svc == "[]" ]] ; then
    echo "Unable to locate the topic-gateway"
    exit 1
  else
    # looks like helm
    port=$(kubectl get svc -l component=topic-gateway -o jsonpath='{.items[0].spec.ports[?(@.name == "topic-gateway")].nodePort}')
  fi
else
  # looks like local
  port=$(kubectl get svc topic-gateway -o jsonpath='{.spec.ports[?(@.name == "http")].nodePort}')
fi
curl -H "Content-Type: text/plain" $(minikube ip):$port/messages/$1 -d "$2"
