= riff is for functions image:https://ci.projectriff.io/api/v1/teams/main/pipelines/riff/badge[Riff Pipeline, link=https://ci.projectriff.io/teams/main/pipelines/riff]

A FaaS for Kubernetes

== Installation of latest release

You can install the latest (v0.0.3) release using link:Getting-Started.adoc[a Helm chart].

The https://github.com/projectriff/riff/tree/v0.0.3/samples[Tag v0.0.3 samples] will work together
with the https://github.com/projectriff/riff/releases[v0.0.3 CLI].

Samples on the git master branch of this repo have been updated to work with recently modified
invokers and can be deployed using the new go CLI. See below for build instructions.

== Developer installation

If you want to run the current development version (git master branch) of riff, read link:Development-Helm-install.adoc[Installing the riff development version using Helm].

=== [[manual]] Manual install of riff

This is the best option if you want to modify the riff components.

==== Prerequisites

You need:

* A running 1.7+ Kubernetes cluster. These instructions assume minikube for now.
+
TIP: We recommend using Minikube v0.23.0 or v0.24.1 and avoiding v0.24.0 due to some DNS issues
+
[source,bash]
----
minikube start
----

* Git installed.

* A Java 8 environment.

* A working Go environment with dep, and clones of the
https://github.com/projectriff/function-sidecar[function-sidecar],
https://github.com/projectriff/function-controller[function-controller],
https://github.com/projectriff/topic-controller[topic-controller],
https://github.com/projectriff/http-gateway[http-gateway],
https://github.com/projectriff/shell-function-invoker[shell-function-invoker], and
https://github.com/projectriff/shell-function-invoker[riff-cli] repositories.
+
[source, bash]
----
cd $(go env GOPATH)   #defaults to ~/go
git clone -o upstream https://github.com/projectriff/function-sidecar src/github.com/projectriff/function-sidecar/
git clone -o upstream https://github.com/projectriff/function-controller src/github.com/projectriff/function-controller/
git clone -o upstream https://github.com/projectriff/topic-controller src/github.com/projectriff/topic-controller/
git clone -o upstream https://github.com/projectriff/http-gateway src/github.com/projectriff/http-gateway/
git clone -o upstream https://github.com/projectriff/shell-function-invoker src/github.com/projectriff/shell-function-invoker/
git clone -o upstream https://github.com/projectriff/riff-cli src/github.com/projectriff/riff-cli/
----

* A clone of the 
https://github.com/projectriff/riff[riff], 
https://github.com/projectriff/java-function-invoker[java-function-invoker], 
https://github.com/projectriff/node-function-invoker[node-function-invoker], 
https://github.com/projectriff/python2-function-invoker[python2-function-invoker] repos.
+
NOTE: These repos should be cloned under a unique root directory since we will be using relative paths during the build.
+
[source, bash]
----
#cd <some_root_dir>
git clone -o upstream https://github.com/projectriff/riff.git
git clone -o upstream https://github.com/projectriff/java-function-invoker.git
git clone -o upstream https://github.com/projectriff/node-function-invoker.git
git clone -o upstream https://github.com/projectriff/python2-function-invoker.git
----

From now on, this README assumes you're running commands from the `riff` repository clone:

[source, bash]
----
cd riff
----

==== Point your local Docker environment to the Docker environment running in minikube

[source, bash]
----
eval $(minikube docker-env)
----

==== Build the core riff components

This builds the Function Sidecar, HTTP Gateway, Topic Controller, Function Controller, and riff CLI:

[source, bash]
----
./build-function-sidecar
./build-http-gateway
./build-topic-controller
./build-function-controller
./build-riff-cli
----

==== Build the other function invokers

This builds the `java-function-invoker`, `node-function-invoker`, `shell-function-invoker`, and `python2-function-invoker`:

[source, bash]
----
./build-function-invokers
----

==== Deploy Kafka/Zookeeper

[source, bash]
----
kubectl apply -f config/kafka
----

==== Deploy the riff custom resources

This creates the Function and Topic CRDs (Custom Resource Definitions):

[source, bash]
----
kubectl apply -f config/types
----

==== Deploy the riff core components

This deploys the HTTP Gateway, Topic Controller, and Function Controller:

[source, bash]
----
kubectl apply -f config
----

If your cluster has RBAC enabled, then you also need to create a Role and a RoleBinding:

[source, bash]
----
kubectl apply -f config/rbac
----

==== To tear it all down

Once you're done playing with riff (see samples below), you can destroy everything created above by running

[source, bash]
----
./teardown
----

== [[samples]]Try Some Samples

With riff running try some of the link:samples/README.adoc[samples].

== Contributing to riff

Please refer to the link:CONTRIBUTING.adoc[Contributors' Guide].

== Maintaining riff

Please refer to the link:MAINTAINING.adoc[Maintainers' Guide].
