= Sk8s: a FaaS for Kubernetes

== Installation

You can install the system using link:Getting-Started.adoc#helm[a Helm chart] or by link:#manual[manually building and deploying] the components.

=== [[manual]]Manual install of Sk8s FaaS

==== Prerequisites

You need:

* A running 1.7 Kubernetes cluster with at least 4GB of memory. These instructions assume minikube for now.
+
----
minikube start --cpus=4 --memory=4096 --disk-size=64g
----

* Git installed.

* A Java 8 environment.

* A working Go environment, with clones of the customized fabric8io/kubernetes-model,
the function-sidecar repository, and the http-gateway repository.
+
----
cd $(go env GOPATH)   #defaults to ~/go
git clone https://github.com/ericbottard/kubernetes-model src/github.com/fabric8io/kubernetes-model/
git clone https://github.com/ericbottard/function-sidecar src/github.com/sk8sio/function-sidecar/
git clone https://github.com/ericbottard/sk8s-http-gateway src/github.com/sk8sio/http-gateway/
----

* A clone of this repo.

----
git clone https://github.com/markfisher/sk8s.git
----

==== Build the kubernetes-model jar Enhanced with the Types for the CustomResources

----
./build-model
----

==== Build the Function Sidecar and HTTP Gateway

----
eval $(minikube docker-env)
./build-function-sidecar
./build-http-gateway
----

==== Setup the Kubernetes environment

Create Function and Topic Custom Resource Definitions:

----
kubectl apply -f config/types
----

Point your Docker environment to the Docker environment running in minikube:

----
eval $(minikube docker-env)
----

==== Build Sk8s FaaS

Build components and create Docker images:

----
./mvnw clean install
./mvnw clean install -f topic-gateway/
./dockerize
----

==== Deploy Kafka/Zookeeper

----
kubectl apply -f config/kafka
----

==== Deploy Sk8s FaaS

----
kubectl apply -f config
----

==== Deploy Metrics (Grafana/Prometheus) and Tracing (Zipkin) Dashboards

----
kubectl apply -f config/prometheus
kubectl apply -f config/grafana
----

----
kubectl apply -f config/zipkin
----

See how to use the link:Monitoring.adoc#dashboards[dashboards].

==== To tear it all down

----
./teardown
----

== [[samples]]Try Some Samples

With the Sk8s FaaS running try some of the link:samples/README.adoc[samples].
