== Prerequisites

* A running 1.7 Kubernetes cluster with at least 4GB of memory
these instructions assume minikube for now. Point your docker environment
to the docker running in minikube.
+
```
minikube start --cpus=4 --memory=4096 --disk-size=64g
eval $(minikube docker-env)
```

* A working Go environment, with a clone of ericbottard's customized fabric8io/kubernetes-model.

```
cd $(go env GOPATH)   #defaults to ~/go
git clone https://github.com/ericbottard/kubernetes-model src/github.com/fabric8io/kubernetes-model/
```

* A clone of this repo.

== Build the kubernetes-model jar Enhanced with Sk8s Types

```
./build-model
```

== Create Sk8s Custom Resource Definitions
```
kubectl apply -f config/types
```

== Build

```
eval $(minikube docker-env)
./mvnw clean package
./dockerize
```

== Create Kafka/Zookeeper

```
kubectl apply -f config/kafka
```

== Deploy

```
kubectl apply -f config
```

== Create a Topic

```
kubectl create -f samples/greetings-topic.yaml
```

== Create a Function

```
kubectl create -f samples/echo-function.yaml
```

== Publish a Message to the Topic

```
./publish greetings hello
```

== Watch Echo Function Sidecar Log

In another terminal
```
#kubectl logs -f -c sidecar [echo-pod-name]
kubectl logs -f -c sidecar $(kubectl get pod -l function=echo -o jsonpath='{.items[0].metadata.name}')
```
== Add a gRPC Function

=== Build the image

```
samples/grpc/dockerize
```

=== Create a Topic (if necessary)

```
kubectl create -f samples/greetings-topic.yaml
```

=== Create the Function

```
kubectl create -f samples/grpc-function
```

== Watch gRPC Function Sidecar Log

In another terminal
```
#kubectl logs -f -c sidecar [grpc-pod-name]
kubectl logs -f -c sidecar $(kubectl get pod -l function=grpc -o jsonpath='{.items[0].metadata.name}')


== Add a Spring Cloud Function

=== Build the JAR

```
./mvnw clean package -f samples/java/greeter/pom.xml
```

=== Build the Docker container for the function code

```
./faas create -f greeter -v v0001 -p samples/java/
```

=== Create a New Topic

```
kubectl create -f samples/names-topic.yaml
```

=== Create the Function

```
kubectl create -f samples/greeter-function.yaml
```

=== Publish a Message

```
./publish names World
```

== Add a Node Function

=== Build the Docker container for the function code

```
./faas create -f square -v v0001 -p samples/node/
```

=== Create a New Topic

```
kubectl create -f samples/numbers-topic.yaml
```

=== Create the Function

```
kubectl create -f samples/square-function.yaml
```

=== Publish a Message

```
./publish numbers 2
```


== Add a Python Function

=== Build the Docker container for the function code

```
./faas create -f sentiments -v v0001 -p samples/python/
```

=== Create New Topics

```
kubectl create -f samples/tweets-topic.yaml
kubectl create -f samples/sentiments-topic.yaml
```

=== Create the Function

```
kubectl create -f samples/sentiments-function.yaml
```

=== Publish a Message

The function performs sentiment analysis on tweets. It accepts JSON and looks only at the `text` field. The input
is in the form of an array (sorry about the escaped quotes).

```
./publish tweets "[{\"text\":\"happy happy happy\"},{\"text\":\"sad sad sad\"}]"
```

== Tear it all down

```
./teardown
```
