== Prerequisites

* A running 1.7 Kubernetes cluster with at least 4GB of memory
these instructions assume minikube for now. Point your docker environment
to the docker running in minikube.

```
minikube start --cpus=4 --memory=4096 --disk-size=64g
eval $(minikube docker-env)
```

* A working Go environment, with a clone of ericbottard's customized fabric8io/kubernetes-model.

```
cd $(go env GOPATH)   #defaults to ~/go
git clone https://github.com/ericbottard/kubernetes-model src/github.com/fabric8io/kubernetes-model/
```

* A clone of this repo.

== Build the kubernetes-model jar Enhanced with Custom Types

```
./build-model
```

== Create Function and Topic Custom Resource Definitions
```
kubectl apply -f config/types
```

== Build

```
eval $(minikube docker-env)
./mvnw clean package
./dockerize
```

== Create Kafka/Zookeeper

```
kubectl apply -f config/kafka
```

== Deploy

```
kubectl apply -f config
```

== Create a Shell Function

=== Build the Docker container for the function code

```
./faas build -n echo -v v0001 -f samples/shell/echo
```

=== Create the Function and Topic(s)

```
./faas apply -f samples/shell/echo
```

=== Tail the Sidecar Log

In another terminal
```
./faas logs -n echo -t
```

=== Publish a Message to the Input Topic

```
./publish greetings hello
```

== Add a Python gRPC Function

=== Build the image

```
samples/python/uppercase/dockerize
```

=== Create the Function and Topic(s)

```
./faas apply -f samples/python/uppercase
```

=== Tail the Sidecar Log

In another terminal

```
./faas logs -n uppercase -t
```

=== Publish a Message to the Input Topic

```
./publish greetings hello
```

== Add a Spring Cloud Function

=== Build the JAR

```
./mvnw clean package -f samples/java/greeter/pom.xml
```

=== Build the Docker container for the function code

```
./faas build -n greeter -v v0001 -f samples/java/greeter
```

=== Create the Function and Topic(s)

```
./faas apply -f samples/java/greeter
```

=== Tail the Sidecar Log

In another terminal

```
./faas logs -n greeter -t
```

=== Publish a Message

```
./publish names World
```

== Add a Node Function

=== Build the Docker container for the function code

```
./faas build -n square -v v0001 -f samples/node/square
```

=== Create the Function and Topic(s)

```
./faas apply -f samples/node/square
```

=== Tail the Sidecar Log

In another terminal

```
./faas logs -n square -t
```

=== Publish a Message

```
./publish numbers 2
```

== Add a Python Function

=== Build the Docker container for the function code

```
./faas build -n sentiments -v v0001 -f samples/python/sentiments
```

=== Create the Function and Topic(s)

```
./faas apply -f samples/python/sentiments
```

=== Tail the Sidecar Log

In another terminal

```
./faas logs -n sentiments -t
```

=== Publish a Message

The function performs sentiment analysis on tweets. It accepts JSON and looks only at the `text` field. The input
is in the form of an array (sorry about the escaped quotes).

```
./publish tweets "[{\"text\":\"happy happy happy\"},{\"text\":\"sad sad sad\"}]"
```

== Tear it all down

```
./teardown
```
