= RIFF: a FaaS for Kubernetes

== Installation

You can install the system using link:Getting-Started.adoc#helm[a Helm chart] or by link:#manual[manually building and deploying] the components.

=== [[manual]]Manual install of RIFF

==== Prerequisites

You need:

* A running 1.7+ Kubernetes cluster with at least 4GB of memory. These instructions assume minikube for now.
+
----
minikube start --cpus=4 --memory=4096 --disk-size=64g
----

* Git installed.

* A Java 8 environment.

* A working Go environment, with clones of the customized fabric8io/kubernetes-model,
the function-sidecar repository, the topic-controller repository and the http-gateway repository.
+
----
cd $(go env GOPATH)   #defaults to ~/go
git clone https://github.com/projectriff/kubernetes-model src/github.com/fabric8io/kubernetes-model/
git clone https://github.com/projectriff/function-sidecar src/github.com/projectriff/function-sidecar/
git clone https://github.com/projectriff/function-sidecar src/github.com/projectriff/function-sidecar/
git clone https://github.com/projectriff/http-gateway src/github.com/projectriff/http-gateway/
----

* A clone of this repo.

----
git clone https://github.com/projectriff/riff.git
----

==== Build the kubernetes-model jar Enhanced with the Types for the CustomResources

----
./build-model
----

==== Build the Function Sidecar, HTTP Gateway and Topic Controller

----
eval $(minikube docker-env)
./build-function-sidecar
./build-http-gateway
./build-topic-controller
----

==== Setup the Kubernetes environment

Create Function and Topic Custom Resource Definitions:

----
kubectl apply -f config/types
----

Point your Docker environment to the Docker environment running in minikube:

----
eval $(minikube docker-env)
----

==== Build RIFF

Build components and create Docker images:

----
./mvnw clean package && ./dockerize
----

==== Deploy Kafka/Zookeeper

----
kubectl apply -f config/kafka
----

==== Deploy RIFF

----
kubectl apply -f config
----

If your cluster has RBAC enabled, then you also need to create a Role and a RoleBinding:

----
kubectl apply -f config/rbac
----

==== Deploy Metrics (Grafana/Prometheus) and Tracing (Zipkin) Dashboards

----
kubectl apply -f config/prometheus
kubectl apply -f config/grafana
----

----
kubectl apply -f config/zipkin
----

See how to use the link:Monitoring.adoc#dashboards[dashboards].

==== To tear it all down

----
./teardown
----

== [[samples]]Try Some Samples

With RIFF running try some of the link:samples/README.adoc[samples].
