= riff is for functions

A FaaS for Kubernetes

[grid="none", frame="none", cols=">,<,>,<,>,<", options="header"]
|=====
2+| Pipelines 2+| Component Builds 2+| Invoker Builds
// 1
| https://github.com/projectriff/ci/blob/master/pipelines/riff.yml[riff]
| image:https://ci.projectriff.io/api/v1/teams/main/pipelines/riff/badge[Riff Pipeline, link=https://ci.projectriff.io/teams/main/pipelines/riff]
| https://github.com/pivotal-cf/pfs-system-test[Acceptance Tests]
| image:https://ci.projectriff.io/api/v1/teams/main/pipelines/riff/jobs/run-riff-system-tests-gke/badge[Acceptance Tests Status, link=https://ci.projectriff.io/teams/main/pipelines/riff/jobs/run-riff-system-tests-gke/builds/latest]
| https://github.com/projectriff/java-function-invoker[Java Invoker]
| image:https://ci.projectriff.io/api/v1/teams/main/pipelines/riff/jobs/build-java-function-invoker-container/badge[Java Invoker, link=https://ci.projectriff.io/teams/main/pipelines/riff/jobs/build-java-function-invoker-container/builds/latest]


// 2
| https://github.com/projectriff/ci/blob/master/pipelines/riff-pr.yml[riff-pr]
| image:https://ci.projectriff.io/api/v1/teams/main/pipelines/riff/badge[Riff Pipeline, link=https://ci.projectriff.io/teams/main/pipelines/riff-pr]
| https://github.com/projectriff/topic-controller[Topic Controller]
| image:https://ci.projectriff.io/api/v1/teams/main/pipelines/riff/jobs/build-topic-controller-container/badge[Topic Controller Status, link=https://ci.projectriff.io/teams/main/pipelines/riff/jobs/build-topic-controller-container/builds/latest]
| https://github.com/projectriff/node-function-invoker[NodeJS Invoker]
| image:https://ci.projectriff.io/api/v1/teams/main/pipelines/riff/jobs/build-node-function-invoker-container/badge[NodeJS Invoker, link=https://ci.projectriff.io/teams/main/pipelines/riff/jobs/build-node-function-invoker-container/builds/latest]

// 3
| https://github.com/projectriff/ci/blob/master/pipelines/dockerimages.yml[dockerimages]
| image:https://ci.projectriff.io/api/v1/teams/main/pipelines/riff/badge[Riff Pipeline, link=https://ci.projectriff.io/teams/main/pipelines/dockerimages]
| https://github.com/projectriff/function-controller[Function Controller]
| image:https://ci.projectriff.io/api/v1/teams/main/pipelines/riff/jobs/build-function-controller-container/badge[Function Controller Status, link=https://ci.projectriff.io/teams/main/pipelines/riff/jobs/build-function-controller-container/builds/latest]
| https://github.com/projectriff/python2-function-invoker[Python2 Invoker]
| image:https://ci.projectriff.io/api/v1/teams/main/pipelines/riff/jobs/build-python2-function-invoker-container/badge[Python2 Invoker Status, link=https://ci.projectriff.io/teams/main/pipelines/riff/jobs/build-python2-function-invoker-containe/builds/latest]

// 4
| |
| https://github.com/projectriff/http-gateway[HTTP Gateway]
| image:https://ci.projectriff.io/api/v1/teams/main/pipelines/riff/jobs/build-http-gateway-container/badge[HTTP Gateway Status, link=https://ci.projectriff.io/teams/main/pipelines/riff/jobs/build-http-gateway-container/builds/latest]
| https://github.com/projectriff/shell-function-invoker[Shell Invoker]
| image:https://ci.projectriff.io/api/v1/teams/main/pipelines/riff/jobs/build-shell-function-invoker-container/badge[Shell Invoker Status, link=https://ci.projectriff.io/teams/main/pipelines/riff/build-shell-function-invoker-container/builds/latest]

// 5
| |
| https://github.com/projectriff/function-sidecar[Function Sidecar]
| image:https://ci.projectriff.io/api/v1/teams/main/pipelines/riff/jobs/build-function-sidecar-container/badge[Function Sidecar Status, link=https://ci.projectriff.io/teams/main/pipelines/riff/jobs/build-function-sidecar-container/builds/latest]
| |

// 6
| |
| https://github.com/projectriff/helm-charts[Helm charts]
| image:https://ci.projectriff.io/api/v1/teams/main/pipelines/riff/jobs/build-riff-chart/badge[Helm Charts]
| |
|=====



== Installation of latest release

You can install the latest release using link:Getting-Started.adoc[a Helm chart]. 

== Developer installation

If you want to develop riff you can install the current development version with the link:Developing-with-Minikube.adoc[Helm chart] or by link:#manual[manually building and deploying] the components.

=== [[manual]] Manual install of riff

==== Prerequisites

You need:

* A running 1.7+ Kubernetes cluster. These instructions assume minikube for now.
+
TIP: We recommend using Minikube v0.23.0 or v0.24.1 and avoiding v0.24.0 due to some DNS issues
+
[source,bash]
----
minikube start
----

* Git installed.

* A Java 8 environment.

* A working Go environment, with clones of the 
https://github.com/projectriff/function-sidecar[function-sidecar], 
https://github.com/projectriff/function-controller[function-controller],
https://github.com/projectriff/topic-controller[topic-controller] and 
https://github.com/projectriff/http-gateway[http-gateway] repositories.
+
[source, bash]
----
cd $(go env GOPATH)   #defaults to ~/go
git clone -o upstream https://github.com/projectriff/function-sidecar src/github.com/projectriff/function-sidecar/
git clone -o upstream https://github.com/projectriff/function-controller src/github.com/projectriff/function-controller/
git clone -o upstream https://github.com/projectriff/topic-controller src/github.com/projectriff/topic-controller/
git clone -o upstream https://github.com/projectriff/http-gateway src/github.com/projectriff/http-gateway/
----

* A clone of the 
https://github.com/projectriff/riff[riff], 
https://github.com/projectriff/java-function-invoker[java-function-invoker], 
https://github.com/projectriff/node-function-invoker[node-function-invoker], 
https://github.com/projectriff/shell-function-invoker[shell-function-invoker] and 
https://github.com/projectriff/python2-function-invoker[python2-function-invoker] repos.
+
NOTE: These repos should be cloned under a unique root directory since we will be using relative paths during the build.
+
[source, bash]
----
#cd <some_root_dir>
git clone -o upstream https://github.com/projectriff/riff.git
git clone -o upstream https://github.com/projectriff/java-function-invoker.git
git clone -o upstream https://github.com/projectriff/node-function-invoker.git
git clone -o upstream https://github.com/projectriff/shell-function-invoker.git
git clone -o upstream https://github.com/projectriff/python2-function-invoker.git
----

From now on, this README assumes you're running commands from the `riff` repository clone:

[source, bash]
----
cd riff
----

==== Point your local Docker environment to the Docker environment running in minikube

[source, bash]
----
eval $(minikube docker-env)
----

==== Build the core riff components

This builds the Function Sidecar, HTTP Gateway, Topic Controller, and Function Controller:

[source, bash]
----
./build-function-sidecar
./build-http-gateway
./build-topic-controller
./build-function-controller
----

==== Build the function invokers

This builds the `java-function-invoker`, `node-function-invoker`, `shell-function-invoker`, and `python2-function-invoker`:

[source, bash]
----
./build-function-invokers
----

==== Deploy Kafka/Zookeeper

[source, bash]
----
kubectl apply -f config/kafka
----

==== Deploy the riff custom resources

This creates the Function and Topic CRDs (Custom Resource Definitions):

[source, bash]
----
kubectl apply -f config/types
----

==== Deploy the riff core components

This deploys the HTTP Gateway, Topic Controller, and Function Controller:

[source, bash]
----
kubectl apply -f config
----

If your cluster has RBAC enabled, then you also need to create a Role and a RoleBinding:

[source, bash]
----
kubectl apply -f config/rbac
----

==== To tear it all down

Once you're done playing with riff (see samples below), you can destroy everything created above by running

[source, bash]
----
./teardown
----

== [[samples]]Try Some Samples

With riff running try some of the link:samples/README.adoc[samples].
