== Prerequisites

* A running 1.7 Kubernetes cluster with at least 4GB of memory
these instructions assume minikube for now. Point your docker environment
to the docker running in minikube.
+
```
minikube start --cpus=4 --memory=4096 --disk-size=64g
eval $(minikube docker-env)
```

* A working Go environment, with a clone of ericbottard's customized fabric8io/kubernetes-model.

```
cd $(go env GOPATH)   #defaults to ~/go
git clone https://github.com/ericbottard/kubernetes-model src/github.com/fabric8io/kubernetes-model/
```

* A clone of this repo.

== Build the kubernetes-model jar Enhanced with Sk8s Types

```
./build-model
```

== Create Sk8s Custom Resource Definitions
```
kubectl apply -f config/types
```

== Build

```
eval $(minikube docker-env)
./mvnw clean package
./dockerize
```

== Create Kafka/Zookeeper

```
kubectl apply -f config/kafka
```

== Deploy

```
kubectl apply -f config
```

== Create a Topic

```
kubectl create -f samples/greetings-topic.yaml
```

== Create a Function

```
kubectl create -f samples/echo-function.yaml
```

== Publish a Message to the Topic

```
./publish greetings hello
```

== Watch Echo Function Sidecar Log

In another terminal
```
#kubectl logs -f -c sidecar [echo-pod-name]
kubectl logs -f -c sidecar $(kubectl get pod -l function=echo -o jsonpath='{.items[0].metadata.name}')
```

== Create sample functions with language support

=== Build the Java function JAR

```
./mvnw clean package -f samples/java/greeter/pom.xml
```

=== Build and deploy sample functions http server

```
docker build -t sk8s/sample-functions samples
kubectl apply -f samples/sample-functions-deployment.yaml
kubectl apply -f samples/sample-functions-svc.yaml
```

== Run a Spring Cloud Function

=== Create a New Topic

```
kubectl create -f samples/names-topic.yaml
```

=== Create the Function

```
kubectl create -f samples/greeter-function.yaml
```

=== Publish a Message

```
./publish names World
```

== Run a Node Function

NOTE: We already built and published all sample functions above

=== Create a New Topic

```
kubectl create -f samples/numbers-topic.yaml
```

=== Create the Function

```
kubectl create -f samples/square-function.yaml
```

=== Publish a Message

```
./publish numbers 2
```

== Tear it all down

```
./teardown
```
