== Prerequisites

* a running 1.7 Kubernetes cluster with at least 4GB of memory
these instructions assume minikube for now, for example:
+
```
minikube start --cpus=4 --memory=4096 --disk-size=64g
```

* A working Go programming environment, with `GOPATH` set (defaults
to `~/go`)

== Build the kubernetes-model jar Enhanced with Sk8s Types
```
cd $GOPATH   #default to ~/go
git clone https://github.com/ericbottard/kubernetes-model src/github.com/fabric8io/kubernetes-model/
cd src/github.com/fabric8io/kubernetes-model/
git checkout sk8s
make
cd <back to the clone of this repo>
```
== Create Sk8s Custom Resource Definitions
```
kubectl apply -f config/types
```

== Build

```
eval $(minikube docker-env)
./mvnw clean package
./dockerize
```

== Create Kafka/Zookeeper

```
kubectl apply -f config/kafka
```

== Deploy

```
kubectl apply -f config
```

== Create a Handler

```
kubectl create -f samples/shell-handler.yaml
```

== Create a Topic

```
kubectl create -f samples/greetings-topic.yaml
```

== Create a Function

```
kubectl create -f samples/echo-function.yaml
```

== Publish a Message to the Topic

```
./publish greetings hello
```

== Watch Results on Minikube

```
# In another terminal
minikube ssh -- tail -f /messages/greetings.log
```

== Add a Spring Cloud Function

=== Build the JAR

```
./mvnw clean package -f samples/java/greeter/pom.xml
```

=== Mount the Samples Folder into the Minikube VM

```
# In yet another terminal
minikube mount samples:/functions
# Leave this running, use another terminal from now on
```

=== Create the Handler

```
kubectl create -f samples/spring-handler.yaml
```

=== Create a New Topic

```
kubectl create -f samples/names-topic.yaml
```

=== Create the Function

```
kubectl create -f samples/greeter-function.yaml
```

=== Publish a Message

```
./publish names World
```

== Add a Node Function

=== Have the Samples Folder Mounted on the Minikube VM
(see above if you haven't done this yet)

=== Create the Handler

```
kubectl create -f samples/node-handler.yaml
```

=== Create a New Topic

```
kubectl create -f samples/numbers-topic.yaml
```

=== Create the Function

```
kubectl create -f samples/square-function.yaml
```

=== Publish a Message

```
./publish numbers 2
```

== Tear it all down

```
./teardown
```
