= riff is for functions

A FaaS for Kubernetes

GKE image:https://ci.faas.to.cf-app.com/api/v1/teams/main/pipelines/riff/jobs/run-riff-system-tests-gke/badge[GKE status] &nbsp; CFCR image:https://ci.faas.to.cf-app.com/api/v1/teams/main/pipelines/riff/jobs/run-riff-system-tests-kubo/badge[CF Container Runtime status]

== Installation

You can install the system using link:Getting-Started.adoc#helm[a Helm chart] or by link:#manual[manually building and deploying] the components.

=== [[manual]] Manual install of riff

==== Prerequisites

You need:

* A running 1.7+ Kubernetes cluster with at least 4GB of memory. These instructions assume minikube for now.
+
TIP: We recommend using Minikube v0.23.0 or v0.24.1 and avoiding v0.24.0 due to some DNS issues
+
[source,bash]
----
minikube start --memory=4096
----

* Git installed.

* A Java 8 environment.

* A working Go environment, with clones of the function-sidecar, function-controller,
topic-controller and http-gateway repositories.
+
[source, bash]
----
cd $(go env GOPATH)   #defaults to ~/go
git clone -o upstream https://github.com/projectriff/function-sidecar src/github.com/projectriff/function-sidecar/
git clone -o upstream https://github.com/projectriff/function-controller src/github.com/projectriff/function-controller/
git clone -o upstream https://github.com/projectriff/topic-controller src/github.com/projectriff/topic-controller/
git clone -o upstream https://github.com/projectriff/http-gateway src/github.com/projectriff/http-gateway/
----

* A clone of the riff, java-function-invoker, node-function-invoker, shell-function-invoker and python2-function-invoker repos.
+
NOTE: These repos should be cloned under a unique root directory since we will be using relative paths during the build.
+
[source, bash]
----
#cd <some_root_dir>
git clone -o upstream https://github.com/projectriff/riff.git
git clone -o upstream https://github.com/projectriff/java-function-invoker.git
git clone -o upstream https://github.com/projectriff/node-function-invoker.git
git clone -o upstream https://github.com/projectriff/shell-function-invoker.git
git clone -o upstream https://github.com/projectriff/python2-function-invoker.git
----

From now on, this README assumes you're running commands from the `riff` repository clone:

[source, bash]
----
cd riff
----

==== Point your local Docker environment to the Docker environment running in minikube:

[source, bash]
----
eval $(minikube docker-env)
----

==== Build the Function Sidecar, HTTP Gateway, and Topic Controller

[source, bash]
----
./build-function-sidecar upstream master
./build-http-gateway upstream master
./build-topic-controller upstream master
----

==== Setup the Kubernetes environment

Create Function and Topic Custom Resource Definitions:

[source, bash]
----
kubectl apply -f config/types
----

==== Build the Function Controller

[source, bash]
----
./build-function-controller upstream master
----

==== Build the java-function-invoker, node-function-invoker, shell-function-invoker and python2-function-invoker

[source, bash]
----
./build-function-invokers upstream master
----

==== Deploy Kafka/Zookeeper

[source, bash]
----
kubectl apply -f config/kafka
----

==== Deploy RIFF

[source, bash]
----
kubectl apply -f config
----

If your cluster has RBAC enabled, then you also need to create a Role and a RoleBinding:

[source, bash]
----
kubectl apply -f config/rbac
----

==== Deploy Tracing (Zipkin) Dashboard

[source, bash]
----
kubectl apply -f config/zipkin
----

See how to use the link:Monitoring.adoc#dashboards[dashboards].

==== To tear it all down

Once you're done playing with riff (see samples below), you can destroy everything created above by running

[source, bash]
----
./teardown
----

== [[samples]]Try Some Samples

With riff running try some of the link:samples/README.adoc[samples].
