#!/bin/bash

svc=$(kubectl get svc -l component=http-gateway -o jsonpath='{.items}')
if [[ $svc == "[]" ]] ; then
  echo "Unable to locate the http-gateway"
  exit 1
fi

type=$(kubectl get svc -l component=http-gateway -o jsonpath='{.items[0].spec.type}')
if [[ $type == "NodePort" ]] ; then
  address=$(minikube ip)
  port=$(kubectl get svc -l component=http-gateway -o jsonpath='{.items[0].spec.ports[?(@.name == "http")].nodePort}')
else
  address=$(kubectl get svc -l component=http-gateway -o jsonpath='{.items[0].status.loadBalancer.ingress[0].ip}')
  if [[ $address == "" ]] ; then
    echo "External IP is not yet available, try in a few ..."
    exit 1
  fi
  port=$(kubectl get svc -l component=http-gateway -o jsonpath='{.items[0].spec.ports[?(@.name == "http")].port}')
fi

curl -H "Content-Type: text/plain" http://$address:$port/requests/$1 -d "$2"
echo ""
