#!/bin/bash

kubectl delete all -l function

kubectl delete functions --all
kubectl delete topics --all

kubectl delete all,svc -l app=riff

kubectl delete crd/functions.projectriff.io
kubectl delete crd/topics.projectriff.io

kubectl delete all,svc -n riff-system -l app=kafka
