#!/bin/bash

kubectl delete functions --all
kubectl delete topics --all
kubectl delete all -l app=sample-functions

kubectl delete all -l app=topic-controller
kubectl delete all -l app=topic-gateway
kubectl delete all -l app=event-dispatcher

kubectl delete all -l function=echo
kubectl delete all -l function=greeter
kubectl delete all -l function=square

kubectl delete crd/functions.extensions.sk8s.io
kubectl delete crd/topics.extensions.sk8s.io

kubectl delete all -l app=kafka
kubectl delete all -l app=zipkin
kubectl delete all -l app=metrics
kubectl delete cm -l app=metrics
