// Code generated by mockery v1.0.0
package mockmetrics

import metrics "github.com/projectriff/riff/message-transport/pkg/transport/metrics"
import mock "github.com/stretchr/testify/mock"

// MetricsReceiver is an autogenerated mock type for the MetricsReceiver type
type MetricsReceiver struct {
	mock.Mock
}

// ConsumerMetrics provides a mock function with given fields:
func (_m *MetricsReceiver) ConsumerMetrics() <-chan metrics.ConsumerAggregateMetric {
	ret := _m.Called()

	var r0 <-chan metrics.ConsumerAggregateMetric
	if rf, ok := ret.Get(0).(func() <-chan metrics.ConsumerAggregateMetric); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan metrics.ConsumerAggregateMetric)
		}
	}

	return r0
}

// ProducerMetrics provides a mock function with given fields:
func (_m *MetricsReceiver) ProducerMetrics() <-chan metrics.ProducerAggregateMetric {
	ret := _m.Called()

	var r0 <-chan metrics.ProducerAggregateMetric
	if rf, ok := ret.Get(0).(func() <-chan metrics.ProducerAggregateMetric); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan metrics.ProducerAggregateMetric)
		}
	}

	return r0
}
