{{- if .Values.create.faas -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-event-dispatcher
  labels:
    app: {{ template "name" . }}
    component: event-dispatcher
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        component: event-dispatcher
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-event-dispatcher
          image: "{{ .Values.eventDispatcher.image.repository }}:{{ .Values.eventDispatcher.image.tag }}"
          imagePullPolicy: {{ .Values.eventDispatcher.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.eventDispatcher.service.internalPort }}
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.eventDispatcher.service.internalPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          ports:
            - containerPort: {{ .Values.eventDispatcher.service.internalPort }}
          env:
          - name: SERVER_PORT
            value: '{{ .Values.eventDispatcher.service.internalPort }}'
          - name: JAVA_TOOL_OPTIONS
            value: '-Xmx512m'
          - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
            value: {{ template "fullname" . }}-kafka:9092
          - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES
            value: {{ template "fullname" . }}-zookeeper:2181
{{- end -}}
