#!/bin/bash

set -ex

cd "$(dirname "$0")"
if [ -e proto ]; then
  rm -fr proto/
fi
mkdir proto
GIT_PATH=https://raw.githubusercontent.com/projectriff/function-proto/master

wget $GIT_PATH/function.proto -P proto

docker build . --rm -t projectriff/grpc-py:0.0.2
