= Helm Charts for Riff

== [[riff]]Instructions for installing riff

Riff offers helm charts for deploying the FaaS and its required services to a Kubernetes Cluster.

For detailed installation instruction see link:https://projectriff.io/docs/getting-started-on-minikube/[Getting started on Minikube] or 
link:https://projectriff.io/docs/getting-started-on-gke/[Getting started on GKE] instructions.

== [[helm]]General Helm Notes

=== [[helm-install]]Install Helm

Helm is comprised of two components: one is the client (helm) the other is the server component (tiller). The helm client runs on your local machine and can be installed using the instructions found https://github.com/kubernetes/helm/blob/master/README.md#install[here]

Once you have the helm client installed you can install the server component.

For a cluster that does not have RBAC enabled use:

[source, bash]
----
helm init
----

[NOTE]
====
It gets a bit more complicated if the cluster has RBAC enabled. The Helm project describes the https://docs.helm.sh/using_helm/#best-practices-for-securing-helm-and-tiller[Best Practices for Securing Helm and Tiller] in their documentation. This can be fairly involved and for less critical development clusters it is easier to configure the Helm tiller server to run with cluster-admin privileges using a service account in the `kube-system` namespace. You should have cluster admin rights and run the following:

[source, bash]
----
kubectl -n kube-system create serviceaccount tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account=tiller
----

====

TIP: To verify that the tiller pod has started execute the following command: `kubectl get pod --namespace kube-system -l app=helm` and you should see the `tiller` pod running.

=== [[riff-repo]]Add the riff charts repository to your helm configuration

Run the following commands to add the repository:

[source, bash]
----
helm repo add projectriff https://riff-charts.storage.googleapis.com
helm repo update
----

Run the following command to see that the `riff` chart is available and also what versions you can install:

[source, bash]
----
helm search riff -l
----
