// Code generated by mockery v1.0.0
package mocktransport

import message "github.com/projectriff/message-transport/pkg/message"
import mock "github.com/stretchr/testify/mock"

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

// Errors provides a mock function with given fields:
func (_m *Producer) Errors() <-chan error {
	ret := _m.Called()

	var r0 <-chan error
	if rf, ok := ret.Get(0).(func() <-chan error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan error)
		}
	}

	return r0
}

// Send provides a mock function with given fields: topic, _a1
func (_m *Producer) Send(topic string, _a1 message.Message) error {
	ret := _m.Called(topic, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, message.Message) error); ok {
		r0 = rf(topic, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
