// Code generated by mockery v1.0.0
package kubectl

import mock "github.com/stretchr/testify/mock"

// MockKubeCtl is an autogenerated mock type for the KubeCtl type
type MockKubeCtl struct {
	mock.Mock
}

// ExecForBytes provides a mock function with given fields: cmdArgs
func (_m *MockKubeCtl) ExecForBytes(cmdArgs []string) ([]byte, error) {
	ret := _m.Called(cmdArgs)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]string) []byte); ok {
		r0 = rf(cmdArgs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(cmdArgs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Exec provides a mock function with given fields: cmdArgs
func (_m *MockKubeCtl) ExecForString(cmdArgs []string) (string, error) {
	ret := _m.Called(cmdArgs)

	var r0 string
	if rf, ok := ret.Get(0).(func([]string) string); ok {
		r0 = rf(cmdArgs)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(cmdArgs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
