= slack-command

[horizontal]
*Language*:: JavaScript
*Function*:: https://github.com/projectriff/riff/blob/master/samples/slack/slack-command/slack_command.js[slack_command.js]
*Protocol*:: HTTP
*Input*:: slack
*Output*:: none (replies, implicitly)

=== Deploy the FaaS

[NOTE]
This example requires a Kubernetes cluster with LoadBalancer support and a public facing IP address. The following
instructions assume you will be running on https://cloud.google.com/kubernetes-engine/[GKE].

Deploy riff with link:../../../Getting-Started.adoc[helm].


=== Build the Docker container for the function code

```

docker build -t <your-dockerhub-repo>/riff-slack-command samples/node/slack/slack-command
```

Where `<your-dockerhub-repo>` is a repository on dockerhub for which you have push permissions, and `<your-tag>`
is anything other than `latest` (not strictly necessary, but probably a best practice).

=== Publish the resulting image

We will generally assume you are able to publish your images to https://hub.docker.com/[dockerhub].

```
docker push <your-dockerhub-repo>/riff-slack-command
```

=== Create the Function and Topic(s)

Assuming your kube config is pointed at GKE,

```
kubectl -n <your-namespace> apply -f <(cat <<EOF
apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: slack
---
apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: slack-command
spec:
  protocol: http
  input: slack
  container:
    image: <your-dockerhub-repo>/riff-slack-command:latest
EOF)
```

where `<your-namespace>` is the Kubernetes namespace in which you would like your function deployed.

=== Set up your integration on Slack

To create your slack slash command (https://api.slack.com/slash-commands), you will need the external IP address
of the riff http gateway.

```
$ kubectl -n get svc -l component=http-gateway
NAME                     TYPE           CLUSTER-IP      EXTERNAL-IP       PORT(S)        AGE
riff-http-gateway        LoadBalancer   10.51.247.194   104.154.118.171   80:30725/TCP   22m
```

You can see from the `EXTERNAL-IP` and `PORT(S)` columns that the external gateway address `http://104.154.118.171:80`
in this case. Since the input topic we configured for the function is named `slack`, configure the
slash command to `POST` to `http://104.154.118.171:80/requests/slack`.

=== Delete your function

```
kubectl -n <your-namespace> delete function slack-command
```
