// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"
import v1alpha1 "github.com/projectriff/riff/kubernetes-crds/pkg/apis/projectriff.io/v1alpha1"

// Deployer is an autogenerated mock type for the Deployer type
type Deployer struct {
	mock.Mock
}

// Deploy provides a mock function with given fields: binding, function
func (_m *Deployer) Deploy(binding *v1alpha1.Binding, function *v1alpha1.Function) error {
	ret := _m.Called(binding, function)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.Binding, *v1alpha1.Function) error); ok {
		r0 = rf(binding, function)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Scale provides a mock function with given fields: binding, replicas
func (_m *Deployer) Scale(binding *v1alpha1.Binding, replicas int) error {
	ret := _m.Called(binding, replicas)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.Binding, int) error); ok {
		r0 = rf(binding, replicas)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Undeploy provides a mock function with given fields: binding
func (_m *Deployer) Undeploy(binding *v1alpha1.Binding) error {
	ret := _m.Called(binding)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.Binding) error); ok {
		r0 = rf(binding)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: binding, function, replicas
func (_m *Deployer) Update(binding *v1alpha1.Binding, function *v1alpha1.Function, replicas int) error {
	ret := _m.Called(binding, function, replicas)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.Binding, *v1alpha1.Function, int) error); ok {
		r0 = rf(binding, function, replicas)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
