// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import v1 "github.com/projectriff/riff/kubernetes-crds/pkg/apis/projectriff.io/v1"

// Deployer is an autogenerated mock type for the Deployer type
type Deployer struct {
	mock.Mock
}

// Deploy provides a mock function with given fields: function
func (_m *Deployer) Deploy(function *v1.Function) error {
	ret := _m.Called(function)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Function) error); ok {
		r0 = rf(function)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Scale provides a mock function with given fields: function, replicas
func (_m *Deployer) Scale(function *v1.Function, replicas int) error {
	ret := _m.Called(function, replicas)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Function, int) error); ok {
		r0 = rf(function, replicas)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Undeploy provides a mock function with given fields: function
func (_m *Deployer) Undeploy(function *v1.Function) error {
	ret := _m.Called(function)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Function) error); ok {
		r0 = rf(function)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: function, replicas
func (_m *Deployer) Update(function *v1.Function, replicas int) error {
	ret := _m.Called(function, replicas)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Function, int) error); ok {
		r0 = rf(function, replicas)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
