// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import cache "k8s.io/client-go/tools/cache"
import extensionsv1beta1 "k8s.io/client-go/listers/extensions/v1beta1"
import mock "github.com/stretchr/testify/mock"

// DeploymentInformer is an autogenerated mock type for the DeploymentInformer type
type DeploymentInformer struct {
	mock.Mock
}

// Informer provides a mock function with given fields:
func (_m *DeploymentInformer) Informer() cache.SharedIndexInformer {
	ret := _m.Called()

	var r0 cache.SharedIndexInformer
	if rf, ok := ret.Get(0).(func() cache.SharedIndexInformer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cache.SharedIndexInformer)
		}
	}

	return r0
}

// Lister provides a mock function with given fields:
func (_m *DeploymentInformer) Lister() extensionsv1beta1.DeploymentLister {
	ret := _m.Called()

	var r0 extensionsv1beta1.DeploymentLister
	if rf, ok := ret.Get(0).(func() extensionsv1beta1.DeploymentLister); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(extensionsv1beta1.DeploymentLister)
		}
	}

	return r0
}
