{{- if .Values.create.crd -}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: functions.projectriff.io
versions:
- name: v1
spec:
  scope: Namespaced
  group: projectriff.io
  version: v1
  names:
    kind: Function
    plural: functions
    singular: function
{{- end -}}
