// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import image "github.com/projectriff/riff/pkg/image"
import mock "github.com/stretchr/testify/mock"

// Docker is an autogenerated mock type for the Docker type
type Docker struct {
	mock.Mock
}

// ImageExists provides a mock function with given fields: name
func (_m *Docker) ImageExists(name string) bool {
	ret := _m.Called(name)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// LoadAndTagImage provides a mock function with given fields: name, digest, file
func (_m *Docker) LoadAndTagImage(name string, digest string, file string) error {
	ret := _m.Called(name, digest, file)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(name, digest, file)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PullImage provides a mock function with given fields: name, directory
func (_m *Docker) PullImage(name string, directory string) (image.Id, error) {
	ret := _m.Called(name, directory)

	var r0 image.Id
	if rf, ok := ret.Get(0).(func(string, string) image.Id); ok {
		r0 = rf(name, directory)
	} else {
		r0 = ret.Get(0).(image.Id)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(name, directory)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PushImage provides a mock function with given fields: name
func (_m *Docker) PushImage(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
