---
apiVersion: projectriff.io/v1alpha1
kind: Function
metadata:
  name: matching-invoker-with-handler
spec:
  container:
    image: rifftest/matching-invoker-with-handler:0.0.1
  input: matching-invoker-with-handler
  protocol: grpc
  windowing:
    size: 1
