// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Copier is an autogenerated mock type for the Copier type
type Copier struct {
	mock.Mock
}

// Copy provides a mock function with given fields: destPath, srcPath
func (_m *Copier) Copy(destPath string, srcPath string) error {
	ret := _m.Called(destPath, srcPath)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(destPath, srcPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
