// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import os "os"

// Utils is an autogenerated mock type for the Utils type
type Utils struct {
	mock.Mock
}

// Copy provides a mock function with given fields: destPath, srcPath
func (_m *Utils) Copy(destPath string, srcPath string) error {
	ret := _m.Called(destPath, srcPath)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(destPath, srcPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: path
func (_m *Utils) Exists(path string) bool {
	ret := _m.Called(path)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Filemode provides a mock function with given fields: path
func (_m *Utils) Filemode(path string) (os.FileMode, error) {
	ret := _m.Called(path)

	var r0 os.FileMode
	if rf, ok := ret.Get(0).(func(string) os.FileMode); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(os.FileMode)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
