// Code generated by mockery v1.0.0. DO NOT EDIT.

package mockextensions

import mock "github.com/stretchr/testify/mock"
import rest "k8s.io/client-go/rest"
import v1beta1 "k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1"

// ApiextensionsV1beta1Interface is an autogenerated mock type for the ApiextensionsV1beta1Interface type
type ApiextensionsV1beta1Interface struct {
	mock.Mock
}

// CustomResourceDefinitions provides a mock function with given fields:
func (_m *ApiextensionsV1beta1Interface) CustomResourceDefinitions() v1beta1.CustomResourceDefinitionInterface {
	ret := _m.Called()

	var r0 v1beta1.CustomResourceDefinitionInterface
	if rf, ok := ret.Get(0).(func() v1beta1.CustomResourceDefinitionInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.CustomResourceDefinitionInterface)
		}
	}

	return r0
}

// RESTClient provides a mock function with given fields:
func (_m *ApiextensionsV1beta1Interface) RESTClient() rest.Interface {
	ret := _m.Called()

	var r0 rest.Interface
	if rf, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}

	return r0
}
