// Code generated by mockery v1.0.0. DO NOT EDIT.

package mockextensions

import discovery "k8s.io/client-go/discovery"
import mock "github.com/stretchr/testify/mock"
import v1beta1 "k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1"

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

// Apiextensions provides a mock function with given fields:
func (_m *Interface) Apiextensions() v1beta1.ApiextensionsV1beta1Interface {
	ret := _m.Called()

	var r0 v1beta1.ApiextensionsV1beta1Interface
	if rf, ok := ret.Get(0).(func() v1beta1.ApiextensionsV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.ApiextensionsV1beta1Interface)
		}
	}

	return r0
}

// ApiextensionsV1beta1 provides a mock function with given fields:
func (_m *Interface) ApiextensionsV1beta1() v1beta1.ApiextensionsV1beta1Interface {
	ret := _m.Called()

	var r0 v1beta1.ApiextensionsV1beta1Interface
	if rf, ok := ret.Get(0).(func() v1beta1.ApiextensionsV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.ApiextensionsV1beta1Interface)
		}
	}

	return r0
}

// Discovery provides a mock function with given fields:
func (_m *Interface) Discovery() discovery.DiscoveryInterface {
	ret := _m.Called()

	var r0 discovery.DiscoveryInterface
	if rf, ok := ret.Get(0).(func() discovery.DiscoveryInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(discovery.DiscoveryInterface)
		}
	}

	return r0
}
