// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import core "github.com/projectriff/riff/pkg/core"
import mock "github.com/stretchr/testify/mock"

// KubectlClient is an autogenerated mock type for the KubectlClient type
type KubectlClient struct {
	mock.Mock
}

// SystemUninstall provides a mock function with given fields: options
func (_m *KubectlClient) SystemUninstall(options core.SystemUninstallOptions) (bool, error) {
	ret := _m.Called(options)

	var r0 bool
	if rf, ok := ret.Get(0).(func(core.SystemUninstallOptions) bool); ok {
		r0 = rf(options)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(core.SystemUninstallOptions) error); ok {
		r1 = rf(options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
