apiVersion: extensions.sk8s.io/v1
kind: Function
metadata:
  name: greeter
spec:
  image: sk8s/java-function-invoker:v0001
  protocol: http
  input: names
  output: greetings
  env:
  - name: FUNCTION_URI
    value: http://sample-functions/java/greeter-1.0.0.jar?functions.Greeter
