apiVersion: extensions.sk8s.io/v1
kind: Function
metadata:
  name: wc
spec:
  image: sk8s/shell-function-invoker:latest
  protocol: stdio
  input: names
  output: greetings
  env:
  - name: FUNCTION_URI
    value: http://sample-functions/script/wordcount.sh
