/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package apis

import "net/url"

// Addressable provides a generic mechanism for a custom resource
// definition to indicate a destination for message delivery.

// Addressable is the schema for the destination information. This is
// typically stored in the object's `status`, as this information may
// be generated by the controller.
// +k8s:deepcopy-gen=true
type Addressable struct {
	URL string `json:"url,omitempty"`
}

func (a *Addressable) Parse() (*url.URL, error) {
	return url.Parse(a.URL)
}
