// Code generated by mockery v1.0.0. DO NOT EDIT.
package docker

import mock "github.com/stretchr/testify/mock"

// MockDocker is an autogenerated mock type for the Docker type
type MockDocker struct {
	mock.Mock
}

// Exec provides a mock function with given fields: command, cmdArgs
func (_m *MockDocker) Exec(command string, cmdArgs ...string) error {
	_va := make([]interface{}, len(cmdArgs))
	for _i := range cmdArgs {
		_va[_i] = cmdArgs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, command)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, ...string) error); ok {
		r0 = rf(command, cmdArgs...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
