// +build !ignore_autogenerated

/*
 * Copyright 2018 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&Function{}, func(obj interface{}) { SetObjectDefaults_Function(obj.(*Function)) })
	scheme.AddTypeDefaultingFunc(&Invoker{}, func(obj interface{}) { SetObjectDefaults_Invoker(obj.(*Invoker)) })
	scheme.AddTypeDefaultingFunc(&Link{}, func(obj interface{}) { SetObjectDefaults_Link(obj.(*Link)) })
	scheme.AddTypeDefaultingFunc(&Topic{}, func(obj interface{}) { SetObjectDefaults_Topic(obj.(*Topic)) })
	return nil
}

func SetObjectDefaults_Function(in *Function) {
	SetDefaults_FunctionSpec(&in.Spec)
}

func SetObjectDefaults_Invoker(in *Invoker) {
	SetDefaults_InvokerSpec(&in.Spec)
	SetObjectDefaults_Function(&in.Spec.FunctionTemplate)
	SetObjectDefaults_Topic(&in.Spec.TopicTemplate)
	SetObjectDefaults_Link(&in.Spec.LinkTemplate)
}

func SetObjectDefaults_Link(in *Link) {
	SetDefaults_LinkSpec(&in.Spec)
}

func SetObjectDefaults_Topic(in *Topic) {
	SetDefaults_TopicSpec(&in.Spec)
}
