= slack-command

[horizontal]
*Language*:: JavaScript
*Function*:: https://github.com/projectriff/riff/blob/master/samples/slack/slack-command/slack_command.js[slack_command.js]
*Protocol*:: HTTP
*Input*:: slack
*Output*:: none (replies, implicitly)

=== Deploy the FaaS

Deploy riff, either manually (https://github.com/projectriff/riff#manual) or with helm
(https://github.com/projectriff/riff/blob/master/Getting-Started.adoc#helm).
For this example to work, your Kubernetes cluster must allow for the creation of
a LoadBalancer with a public facing IP address.

=== Build the Docker container for the function code

```
docker build -t <your-dockerhub-repo>:<your-tag> slack-command
```

Where `<your-dockerhub-repo>` is a repository on dockerhub for which you have push permissions, and `<your-tag>`
is anything other than `latest` (not strictly necessary, but probably a best practice).

=== Publish the resulting image

This step is of special concern when deploying to GKE, as minikube is capable of having both the docker daemon
(which builds the images) and the registry (which kubernetes pulls from) on your local machine. In the GKE case,
we will generally assume you are able to publish your images to dockerhub.

```
docker push <your-dockerhub-repo>:<your-tag>
```

=== Create the Function and Topic(s)

Assuming your kube config is pointed at GKE,

```
kubectl -n <your-namespace> apply -f <(cat <<EOF
apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: slack
---
apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: slack-command
spec:
  protocol: http
  input: slack
  container:
    image: <your-dockerhub-repo>:<your-tag>
EOF)
```

where `<your-namespace>` is the Kubernetes namespace in which you would like your function deployed.

=== Set up your integration on Slack

When creating your slack slash command (https://api.slack.com/slash-commands), consider the below command
with output.

```
$ kubectl -n <your-namespace> get svc -l component=http-gateway
NAME                     TYPE           CLUSTER-IP      EXTERNAL-IP       PORT(S)        AGE
riff-http-gateway        LoadBalancer   10.51.247.194   104.154.118.171   80:30725/TCP   22m
```

We can see from the `EXTERNAL-IP` and `PORT(S)` columns that our gateway should be reachable at `http://104.154.118.171:80`
in this case. Since the topic we configured in the previous step was called `slack`, then we should configure our
slash command to send `POST` requests to `http://104.154.118.171:80/requests/slack`.

=== Delete your function

```
kubectl -n <your-namespace> delete function slack-command
```
