= Message Transport

== Purpose
The *message transport* is a https://projectriff.io/[Riff] component that enables the HTTP gateway to send messages
to function pods and, when appropriate, to receive replies.

It provides a message type and an abstract transport interface for sending and
receiving messages. It also provides an implementation of the transport interface
based on https://kafka.apache.org/[Apache Kafka].

== Development

The code in this repository is written in Go.

=== Get the source
[source, bash]
----
go get github.com/projectriff/riff
cd $(go env GOPATH)/github.com/projectriff/riff/message-transport
----

=== Building

This component is a dependency of the
https://github.com/projectriff/riff/tree/master/http-gateway[http-gateway]
and https://github.com/projectriff/riff/tree/master/function-sidecar[function-sidecar] components
and is built by them.

You can check that the code in this component compiles cleanly by issuing:
[source, bash]
----
make build
----

=== Testing

Ensure Kafka (with `auto.create.topics.enable=true`, which is the default) and Zookeeper are running locally,
then issue:
[source, bash]
----
KAFKA_BROKERS=localhost:9092 make test
----

== Generating Mocks

Mocks can be regenerated as follows _and should then be checked in_:
[source, bash]
----
make gen-mocks
----

You can verify that generated mocks which are committed or staged are up to date using:
[source, bash]
----
make verify-mocks
----
