// Code generated by mockery v1.0.0. DO NOT EDIT.

package mockkustomize

import kustomize "github.com/projectriff/riff/pkg/core/kustomize"
import mock "github.com/stretchr/testify/mock"
import url "net/url"

// Kustomizer is an autogenerated mock type for the Kustomizer type
type Kustomizer struct {
	mock.Mock
}

// ApplyLabel provides a mock function with given fields: resourceUri, label
func (_m *Kustomizer) ApplyLabel(resourceUri *url.URL, label *kustomize.Label) ([]byte, error) {
	ret := _m.Called(resourceUri, label)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(*url.URL, *kustomize.Label) []byte); ok {
		r0 = rf(resourceUri, label)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*url.URL, *kustomize.Label) error); ok {
		r1 = rf(resourceUri, label)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
