// Code generated by mockery v1.0.0. DO NOT EDIT.

package streaming

import (
	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/projectriff/system/pkg/apis/streaming/v1alpha1"
)

// MockStreamProvisionerClient is an autogenerated mock type for the StreamProvisionerClient type
type MockStreamProvisionerClient struct {
	mock.Mock
}

// ProvisionStream provides a mock function with given fields: stream, provisionerURL
func (_m *MockStreamProvisionerClient) ProvisionStream(stream *v1alpha1.Stream, provisionerURL string) (*StreamAddress, error) {
	ret := _m.Called(stream, provisionerURL)

	var r0 *StreamAddress
	if rf, ok := ret.Get(0).(func(*v1alpha1.Stream, string) *StreamAddress); ok {
		r0 = rf(stream, provisionerURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*StreamAddress)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1alpha1.Stream, string) error); ok {
		r1 = rf(stream, provisionerURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
