/*
 * Copyright 2018 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// FunctionListerExpansion allows custom methods to be added to
// FunctionLister.
type FunctionListerExpansion interface{}

// FunctionNamespaceListerExpansion allows custom methods to be added to
// FunctionNamespaceLister.
type FunctionNamespaceListerExpansion interface{}

// InvokerListerExpansion allows custom methods to be added to
// InvokerLister.
type InvokerListerExpansion interface{}

// InvokerNamespaceListerExpansion allows custom methods to be added to
// InvokerNamespaceLister.
type InvokerNamespaceListerExpansion interface{}

// LinkListerExpansion allows custom methods to be added to
// LinkLister.
type LinkListerExpansion interface{}

// LinkNamespaceListerExpansion allows custom methods to be added to
// LinkNamespaceLister.
type LinkNamespaceListerExpansion interface{}

// TopicListerExpansion allows custom methods to be added to
// TopicLister.
type TopicListerExpansion interface{}

// TopicNamespaceListerExpansion allows custom methods to be added to
// TopicNamespaceLister.
type TopicNamespaceListerExpansion interface{}
