// Code generated by mockery v1.0.0. DO NOT EDIT.

package mockbuildfactory

import core "github.com/projectriff/riff/pkg/core"
import mock "github.com/stretchr/testify/mock"
import pack "github.com/buildpack/pack"

// BuildFactory is an autogenerated mock type for the BuildFactory type
type BuildFactory struct {
	mock.Mock
}

// BuildConfigFromFlags provides a mock function with given fields: flags
func (_m *BuildFactory) BuildConfigFromFlags(flags *pack.BuildFlags) (core.Build, error) {
	ret := _m.Called(flags)

	var r0 core.Build
	if rf, ok := ret.Get(0).(func(*pack.BuildFlags) core.Build); ok {
		r0 = rf(flags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Build)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*pack.BuildFlags) error); ok {
		r1 = rf(flags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
