// Code generated by protoc-gen-go. DO NOT EDIT.
// source: function.proto

/*
Package function is a generated protocol buffer package.

It is generated from these files:
	function.proto

It has these top-level messages:
	Message
*/
package function

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Payload []byte                          `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers map[string]*Message_HeaderValue `protobuf:"bytes,2,rep,name=headers" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetHeaders() map[string]*Message_HeaderValue {
	if m != nil {
		return m.Headers
	}
	return nil
}

type Message_HeaderValue struct {
	Values []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *Message_HeaderValue) Reset()                    { *m = Message_HeaderValue{} }
func (m *Message_HeaderValue) String() string            { return proto.CompactTextString(m) }
func (*Message_HeaderValue) ProtoMessage()               {}
func (*Message_HeaderValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Message_HeaderValue) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "function.Message")
	proto.RegisterType((*Message_HeaderValue)(nil), "function.Message.HeaderValue")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MessageFunction service

type MessageFunctionClient interface {
	Call(ctx context.Context, opts ...grpc.CallOption) (MessageFunction_CallClient, error)
}

type messageFunctionClient struct {
	cc *grpc.ClientConn
}

func NewMessageFunctionClient(cc *grpc.ClientConn) MessageFunctionClient {
	return &messageFunctionClient{cc}
}

func (c *messageFunctionClient) Call(ctx context.Context, opts ...grpc.CallOption) (MessageFunction_CallClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_MessageFunction_serviceDesc.Streams[0], c.cc, "/function.MessageFunction/Call", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageFunctionCallClient{stream}
	return x, nil
}

type MessageFunction_CallClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type messageFunctionCallClient struct {
	grpc.ClientStream
}

func (x *messageFunctionCallClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageFunctionCallClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for MessageFunction service

type MessageFunctionServer interface {
	Call(MessageFunction_CallServer) error
}

func RegisterMessageFunctionServer(s *grpc.Server, srv MessageFunctionServer) {
	s.RegisterService(&_MessageFunction_serviceDesc, srv)
}

func _MessageFunction_Call_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageFunctionServer).Call(&messageFunctionCallServer{stream})
}

type MessageFunction_CallServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type messageFunctionCallServer struct {
	grpc.ServerStream
}

func (x *messageFunctionCallServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageFunctionCallServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MessageFunction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "function.MessageFunction",
	HandlerType: (*MessageFunctionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Call",
			Handler:       _MessageFunction_Call_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "function.proto",
}

func init() { proto.RegisterFile("function.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2b, 0xcd, 0x4b,
	0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xee,
	0x33, 0x72, 0xb1, 0xfb, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x0a, 0x49, 0x70, 0xb1, 0x17, 0x24,
	0x56, 0xe6, 0xe4, 0x27, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0xc1, 0xb8, 0x42, 0x16,
	0x5c, 0xec, 0x19, 0xa9, 0x89, 0x29, 0xa9, 0x45, 0xc5, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46,
	0x72, 0x7a, 0x70, 0x13, 0xa1, 0xba, 0xf5, 0x3c, 0x20, 0x0a, 0x5c, 0xf3, 0x4a, 0x8a, 0x2a, 0x83,
	0x60, 0xca, 0xa5, 0x54, 0xb9, 0xb8, 0x21, 0x12, 0x61, 0x89, 0x39, 0xa5, 0xa9, 0x42, 0x62, 0x5c,
	0x6c, 0x65, 0x20, 0x46, 0xb1, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0x67, 0x10, 0x94, 0x27, 0x15, 0xc9,
	0xc5, 0x83, 0xac, 0x5f, 0x48, 0x80, 0x8b, 0x39, 0x3b, 0xb5, 0x12, 0xec, 0x0c, 0xce, 0x20, 0x10,
	0x53, 0xc8, 0x98, 0x8b, 0x15, 0xac, 0x56, 0x82, 0x49, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x16, 0x97,
	0x03, 0xc0, 0xf6, 0x04, 0x41, 0xd4, 0x5a, 0x31, 0x59, 0x30, 0x1a, 0xb9, 0x72, 0xf1, 0x43, 0x55,
	0xb8, 0x41, 0x75, 0x08, 0x19, 0x71, 0xb1, 0x38, 0x27, 0xe6, 0xe4, 0x08, 0x09, 0x62, 0x18, 0x22,
	0x85, 0x29, 0xa4, 0xc4, 0xa0, 0xc1, 0x68, 0xc0, 0x98, 0xc4, 0x06, 0x0e, 0x39, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x3b, 0xfd, 0x62, 0xbe, 0x4b, 0x01, 0x00, 0x00,
}
