/*
Copyright 2019 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/projectriff/system/pkg/apis/streaming/v1alpha1"
)

// FakePulsarGateways implements PulsarGatewayInterface
type FakePulsarGateways struct {
	Fake *FakeStreamingV1alpha1
	ns   string
}

var pulsargatewaysResource = schema.GroupVersionResource{Group: "streaming.projectriff.io", Version: "v1alpha1", Resource: "pulsargatewaies"}

var pulsargatewaysKind = schema.GroupVersionKind{Group: "streaming.projectriff.io", Version: "v1alpha1", Kind: "PulsarGateway"}

// Get takes name of the pulsarGateway, and returns the corresponding pulsarGateway object, and an error if there is any.
func (c *FakePulsarGateways) Get(name string, options v1.GetOptions) (result *v1alpha1.PulsarGateway, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pulsargatewaysResource, c.ns, name), &v1alpha1.PulsarGateway{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PulsarGateway), err
}

// List takes label and field selectors, and returns the list of PulsarGateways that match those selectors.
func (c *FakePulsarGateways) List(opts v1.ListOptions) (result *v1alpha1.PulsarGatewayList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pulsargatewaysResource, pulsargatewaysKind, c.ns, opts), &v1alpha1.PulsarGatewayList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PulsarGatewayList{ListMeta: obj.(*v1alpha1.PulsarGatewayList).ListMeta}
	for _, item := range obj.(*v1alpha1.PulsarGatewayList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pulsarGateways.
func (c *FakePulsarGateways) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pulsargatewaysResource, c.ns, opts))

}

// Create takes the representation of a pulsarGateway and creates it.  Returns the server's representation of the pulsarGateway, and an error, if there is any.
func (c *FakePulsarGateways) Create(pulsarGateway *v1alpha1.PulsarGateway) (result *v1alpha1.PulsarGateway, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pulsargatewaysResource, c.ns, pulsarGateway), &v1alpha1.PulsarGateway{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PulsarGateway), err
}

// Update takes the representation of a pulsarGateway and updates it. Returns the server's representation of the pulsarGateway, and an error, if there is any.
func (c *FakePulsarGateways) Update(pulsarGateway *v1alpha1.PulsarGateway) (result *v1alpha1.PulsarGateway, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pulsargatewaysResource, c.ns, pulsarGateway), &v1alpha1.PulsarGateway{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PulsarGateway), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePulsarGateways) UpdateStatus(pulsarGateway *v1alpha1.PulsarGateway) (*v1alpha1.PulsarGateway, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(pulsargatewaysResource, "status", c.ns, pulsarGateway), &v1alpha1.PulsarGateway{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PulsarGateway), err
}

// Delete takes name of the pulsarGateway and deletes it. Returns an error if one occurs.
func (c *FakePulsarGateways) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(pulsargatewaysResource, c.ns, name), &v1alpha1.PulsarGateway{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePulsarGateways) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pulsargatewaysResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PulsarGatewayList{})
	return err
}

// Patch applies the patch and returns the patched pulsarGateway.
func (c *FakePulsarGateways) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PulsarGateway, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pulsargatewaysResource, c.ns, name, pt, data, subresources...), &v1alpha1.PulsarGateway{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PulsarGateway), err
}
