apiVersion: extensions.sk8s.io/v1
kind: Topic
metadata:
  name: names
---

apiVersion: extensions.sk8s.io/v1
kind: Topic
metadata:
  name: greetings
---

apiVersion: extensions.sk8s.io/v1
kind: Function
metadata:
  name: greeter
spec:
  protocol: http
  input: names
  output: greetings
  container:
    image: sk8s/greeter:v0001
    env:
    - name: FUNCTION_URI
      value: file:///functions/function.jar?functions.Greeter
