/*
Copyright 2019 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v1alpha1 "github.com/projectriff/riff/system/pkg/apis/streaming/v1alpha1"
	scheme "github.com/projectriff/riff/system/pkg/client/clientset/versioned/scheme"
)

// InMemoryGatewaysGetter has a method to return a InMemoryGatewayInterface.
// A group's client should implement this interface.
type InMemoryGatewaysGetter interface {
	InMemoryGateways(namespace string) InMemoryGatewayInterface
}

// InMemoryGatewayInterface has methods to work with InMemoryGateway resources.
type InMemoryGatewayInterface interface {
	Create(*v1alpha1.InMemoryGateway) (*v1alpha1.InMemoryGateway, error)
	Update(*v1alpha1.InMemoryGateway) (*v1alpha1.InMemoryGateway, error)
	UpdateStatus(*v1alpha1.InMemoryGateway) (*v1alpha1.InMemoryGateway, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.InMemoryGateway, error)
	List(opts v1.ListOptions) (*v1alpha1.InMemoryGatewayList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.InMemoryGateway, err error)
	InMemoryGatewayExpansion
}

// inMemoryGateways implements InMemoryGatewayInterface
type inMemoryGateways struct {
	client rest.Interface
	ns     string
}

// newInMemoryGateways returns a InMemoryGateways
func newInMemoryGateways(c *StreamingV1alpha1Client, namespace string) *inMemoryGateways {
	return &inMemoryGateways{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the inMemoryGateway, and returns the corresponding inMemoryGateway object, and an error if there is any.
func (c *inMemoryGateways) Get(name string, options v1.GetOptions) (result *v1alpha1.InMemoryGateway, err error) {
	result = &v1alpha1.InMemoryGateway{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("inmemorygateways").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of InMemoryGateways that match those selectors.
func (c *inMemoryGateways) List(opts v1.ListOptions) (result *v1alpha1.InMemoryGatewayList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.InMemoryGatewayList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("inmemorygateways").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested inMemoryGateways.
func (c *inMemoryGateways) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("inmemorygateways").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a inMemoryGateway and creates it.  Returns the server's representation of the inMemoryGateway, and an error, if there is any.
func (c *inMemoryGateways) Create(inMemoryGateway *v1alpha1.InMemoryGateway) (result *v1alpha1.InMemoryGateway, err error) {
	result = &v1alpha1.InMemoryGateway{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("inmemorygateways").
		Body(inMemoryGateway).
		Do().
		Into(result)
	return
}

// Update takes the representation of a inMemoryGateway and updates it. Returns the server's representation of the inMemoryGateway, and an error, if there is any.
func (c *inMemoryGateways) Update(inMemoryGateway *v1alpha1.InMemoryGateway) (result *v1alpha1.InMemoryGateway, err error) {
	result = &v1alpha1.InMemoryGateway{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("inmemorygateways").
		Name(inMemoryGateway.Name).
		Body(inMemoryGateway).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *inMemoryGateways) UpdateStatus(inMemoryGateway *v1alpha1.InMemoryGateway) (result *v1alpha1.InMemoryGateway, err error) {
	result = &v1alpha1.InMemoryGateway{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("inmemorygateways").
		Name(inMemoryGateway.Name).
		SubResource("status").
		Body(inMemoryGateway).
		Do().
		Into(result)
	return
}

// Delete takes name of the inMemoryGateway and deletes it. Returns an error if one occurs.
func (c *inMemoryGateways) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("inmemorygateways").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *inMemoryGateways) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("inmemorygateways").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched inMemoryGateway.
func (c *inMemoryGateways) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.InMemoryGateway, err error) {
	result = &v1alpha1.InMemoryGateway{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("inmemorygateways").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
